Refactoring the `Qasm3Visitor`
qBraid/qbraid-qir pull request #142
Opened 2024-08-15 08:58 UTC by TheGupta2012

## Summary of changes
- With the addition of new constructs in the visitor, a refactoring was needed for the module 
- Validators, helpers and some other methods were factored out of the `Qasm3Visitor`. These were independent of the `self` and moved out to a separate utility class. Moreover, it made sense to keep all the `_visit_*` methods in the visitor.
- Imports for `openqasm3` were also moved to a different file
- One possible separation could also be done based on the constructs i.e. `GateUtils`, `VariableUtils`, etc. but felt a bit of an overkill

@ryanhill1 would like to hear your thoughts on this too, thanks!

2024-08-20 15:10 UTC, ryanhill1 requested changes
1. Let's remove the `qasm3.utils.imports` file and instead use namespace imports in `qasm3.visitor` and other files that have big import blocks.
2. Please refactor to eliminate any ascending relative imports. This can be done either by  moving all of files within `qasm3.utils` up to the `qasm3` module level, or potentially with some clever inversion of the module structure. In the former, there would still only be 8 python files within the top-level `qasm3` module, which isn't that bad.

See comments below.

2024-08-20 15:10 UTC, ryanhill1 commented on qbraid_qir/qasm3/utils/maps.py
> +from ..linalg import kak_decomposition_angles
This is a personal preference, but I'm not a huge fan of upwards i.e. ascending relative imports as they disrupt module hierarchy and often create circular imports.

2024-08-20 15:10 UTC, ryanhill1 commented on qbraid_qir/qasm3/utils/imports.py
A dedicated file for imports isn't great practice. A better way to condense import statements in a given file is to use namespace imports instead of explicit imports. For example, instead of: 

```python
from openqasm3.ast import (
    AliasStatement,
   ...
)


if instance(stmnt, AliasStatement):
    ...

```

this would become

```python
import openqasm3.ast as ast

if instance(stmnt, ast.AliasStatement):
    ...
```

- **Explicit imports** are useful when you need only a few specific items from a module, and it's clear from the context what they are.
- **Namespace imports** are beneficial when working with large modules, and to avoid conflicts with local names or when you want clarity about the origin of each used component.

2024-08-20 15:10 UTC, ryanhill1 commented on qbraid_qir/qasm3/visitor.py
> +from .utils.imports import *
Instead of doing a wildcard import of a module filled with explicit imports, let's just use a namespace import. See comment above.

2024-08-21 05:46 UTC, TheGupta2012 commented on qbraid_qir/qasm3/utils/maps.py
> +from ..linalg import kak_decomposition_angles
I think having the utilities at the base level is fine too, 8 files aren't much

2024-08-21 21:05 UTC, ryanhill1 requested changes
Overall looking much better! Last few things to address which I mention in more detail below:

- Making sure all functions have appropriate type hints (this will also help make  https://github.com/qBraid/qbraid-qir/issues/145 easier)
- Combine in the `print_err_location` and exception raising by either modifying the existing `Qasm3ConversionError` exception class or creating a helper function that both raises the exception and logs/prints the element line/column traceback.
- Rename the `visitor_utils` file and `Qasm3VisitorUtils` class to something a bit more descriptive. Regroup validators / analyzers / transformers as necessary.

2024-08-21 21:05 UTC, ryanhill1 commented on qbraid_qir/qasm3/expressions.py
Please add type hints to all methods to comply with `py.typed`

2024-08-21 21:05 UTC, ryanhill1 commented on qbraid_qir/qasm3/visitor_utils.py
> +class Qasm3VisitorUtils:
Can make this class name a bit more descriptive e.g. something to do with "validator" or "analyzer"? Same with the file name. I generally just don't like using "utils" because it's so broad, it could mean anything. For consistency, could even split the validators into one class and the analyzer / transformer methods into another, and then name them accordingly. Anything other than "utils"

2024-08-21 21:05 UTC, ryanhill1 commented on qbraid_qir/qasm3/visitor_utils.py
> +    def print_err_location(element: Span) -> None:
It seems like we use the `print_err_location` and `raise Qasm3ConversionError` on back-to-back lines repeatedly throughout this qasm3 module. We could potentially eliminate a lot of redundancy by modifying the `Qasm3ConversionError` class so that in addition to a custom error message, it accepts a second (optional) argument for the element that if given, either logs the start line/column or adds it to the error message. Or, if `print_err_location` is used before raising other exceptions as well and not just `Qasm3ConversionError`, we could instead create a helper function that takes as argument an exception to raise, an optional raised from exception, and an optional element (Span), and then both raise the exception and log the start line/column from within a single function call.

2024-08-21 21:05 UTC, ryanhill1 commented on qbraid_qir/qasm3/visitor_utils.py
> +        if not reqd_type:
Is this checking if `reqd_type` is `None` or `False`? type hint would be helpful

2024-08-22 04:55 UTC, TheGupta2012 commented on qbraid_qir/qasm3/visitor_utils.py
> +class Qasm3VisitorUtils:
Okay got it

2024-08-22 04:57 UTC, TheGupta2012 commented on qbraid_qir/qasm3/visitor_utils.py
> +    def print_err_location(element: Span) -> None:
I agree that the approach to create a helper method would reduce redundancy.

2024-08-22 11:00 UTC, TheGupta2012 commented
- Hi @ryanhill1 , I have incorporated the comments and segregated the validator, transformer and analyser into respective files. 
- I have also changed the structure of these classes to include an [attribute which refers to the `BasicQasmVisitor` object](https://github.com/qBraid/qbraid-qir/pull/142/commits/80662444a5c8ad8d61e4057c78f65c5ff60d3ccd#diff-de65fad9d5e9503ce107d80cf4435b642e6edc96da50ed8ebdeb560a2cfaddb0R37). This will remove the dependency of the from the function calls. Methods referring to the object are now `classmethod`s and reference this object internally.

2024-08-22 14:30 UTC, ryanhill1 requested changes
These updates look great! If you could just address the two lines of unreachable code I noted below either by updating the typehint, or removing them. After that it should be good

*Edit*: Also, is the [supported conversions table](https://github.com/qBraid/qbraid-qir/tree/main/qbraid_qir/qasm3#supported-conversions-status-table) up to date? And if not, could you update it? Thanks!

2024-08-22 14:30 UTC, ryanhill1 commented on qbraid_qir/qasm3/analyzer.py
> +            )
Based on the type hint `condition: Union[UnaryExpression, BinaryExpression, IndexExpression]`, this code is unreachable.

2024-08-22 14:30 UTC, ryanhill1 commented on qbraid_qir/qasm3/transformer.py
> +        return None, None
Based on the type hint `condition: Union[UnaryExpression, BinaryExpression, IndexExpression]`, this line is unreachable

2024-08-22 17:44 UTC, TheGupta2012 commented
Sure, will change. Also, some type hints are still left but I'll address them in the `mypy` issue

2024-08-22 19:17 UTC, ryanhill1 approved these changes

2024-08-22 19:17 UTC, merged